server:
  port: 8888
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false # false - queue; true - topic

myqueue: boot-activema-queue
